openapi: 3.0.0

info:
 version: '2'
 title: 'LBAW ATGO Web API'
 description: 'Web Resources Specification (A7) for ATGO, Revision for (A9)'

servers:
# Added by API Auto Mocking Plugin
- url: http://lbaw.fe.up.pt
  description: Production server

externalDocs:
 description: Find more info here.
 url: https://web.fe.up.pt/~ssn/wiki/teach/lbaw/medialib/a07

tags:
 - name: 'M01: Authentication and Profile'
 - name: 'M02: User Administration and Static pages'
 - name: 'M03: Store'
 - name: 'M04: Reviews'
 - name: 'M05: Cart'

paths:
 /login:
   get:
     operationId: R101
     summary: 'R101: Login Form'
     description: 'Provide login form. Access: PUB'
     tags:
       - 'M01: Authentication and Profile'
     responses:
       '200':
         description: 'Ok. Show Log-in UI'
   post:
     operationId: R102
     summary: 'R102: Login Action'
     description: 'Processes the login form submission. Access: PUB'
     tags:
       - 'M01: Authentication and Profile'

     requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               email:
                 type: string
               password:
                 type: string
             required:
                  - email
                  - password

     responses:
       '302':
         description: 'Redirect after processing the login credentials.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful authentication. Redirect to product page'
                 value: '/products'
               302Error:
                 description: 'Failed authentication. Redirect to login form.'
                 value: '/login'

 /logout:

   post:
     operationId: R103
     summary: 'R103: Logout Action'
     description: 'Logout the current authenticated user. Access: USR, ADM'
     tags:
       - 'M01: Authentication and Profile'
     responses:
       '302':
         description: 'Redirect after processing logout.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful logout. Redirect to login form.'
                 value: '/login'

 /register:
   get:
     operationId: R104
     summary: 'R104: Register Form'
     description: 'Provide new user registration form. Access: PUB'
     tags:
       - 'M01: Authentication and Profile'
     responses:
       '200':
         description: 'Ok. Show Sign-Up UI'

   post:
     operationId: R105
     summary: 'R105: Register Action'
     description: 'Processes the new user registration form submission. Access: PUB'
     tags:
       - 'M01: Authentication and Profile'

     requestBody:
       required: true
       content:
         application/x-www-form-urlencoded:
           schema:
             type: object
             properties:
               name:
                 type: string
               email:
                 type: string
               password:
                 type: string
             required:
                                    - name
                                    - email
                                    - password
                                    

     responses:
       '302':
         description: 'Redirect after processing the new user information.'
         headers:
           Location:
             schema:
               type: string
             examples:
               302Success:
                 description: 'Successful authentication. Redirect to products page.'
                 value: '/products/'
               302Failure:
                 description: 'Failed authentication. Redirect to login form.'
                 value: '/login'

 /users/{id}:
   get:
     operationId: R106
     summary: 'R106: View user profile'
     description: 'Show the individual user profile. Access: USR'
     tags:
       - 'M01: Authentication and Profile'

     parameters:
       - in: path
         name: id
         schema:
           type: integer
         required: true

     responses:
       '200':
         description: 'Ok. Show User Profile UI'
 
 /showOrders:
   get:
     operationId: R107
     summary: 'R107: View user purchase history'
     description: 'Show the individual user purchase history. Access: OWN'
     tags:
       - 'M01: Authentication and Profile'
     parameters:
       - in: path
         name: id
         schema:
           type: integer
         required: true
         
     responses:
       '200':
         description: 'Ok. Show User Purchase History UI'

 /search:
   get:
     operationId: R201
     summary: 'R201: Search products API'
     description: 'Searches for products Access: PUB.'

     tags:
       - 'M03: Store'

     parameters:
       - in: query
         name: query
         description: String to use for full-text search
         schema:
           type: string
         required: false
     responses:
       '200':
         description: Success
         content:
           application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                   id:
                     type: string
                   name:
                     type: string
                   price:
                     type: string
                   score:
                     type: string
                   description:
                     type: string
                   gender: 
                     type: string
               example:
                 - id: 1
                   name: Nike shoe
                   price: 27.69
                   score: 4
                   PrimaryColor:  Grey
                   SecondaryColor:  Grey
                   sizeEU: 40
 /products/{id}:
   get:
    operationId: R202
    summary: 'R202: View product details'
    description: 'Show the page with the information of a product . Access: PUB'
    tags:
     - 'M03: Store'

    parameters:
     - in: path
       name: id
       schema:
         type: integer
       required: true

    responses:
     '200':
       description: 'Ok. Show Product UI'
     '400':
       description: 'Product not found'

 /products/:
   get:
    operationId: R203
    summary: 'R203: View products'
    description: 'Show the page a list of a products . Access: PUB'
    tags:
     - 'M03: Store'

    responses:
     '200':
       description: 'Ok. Show Product UI'
     '400':
       description: 'Product not found'
       
 /cart:
    get:
     operationId: R401
     summary: 'R401: View cart of the user'
     description: 'Show the page with the cart of a user . Access: OWN'
     tags:
      - 'M05: Cart'

     parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true

     responses:
      '200':
        description: 'Ok. Show Cart UI'
        
 /api/cart:
   post:
    operationId: R402
    summary: 'R402: Add product to cart'
    description: 'AJAX Request: Adds a chosen quantity of a produt to the cart of a user. Access: OWN'
    tags: 
     - 'M05: Cart'
     
    requestBody:
      required: true
      content:
        application/json:
         schema:
          type: object
          properties:
            id:
              type: integer
            quantity:
              type: integer
      
    responses:
      '200':
       description: 'Sucessfully added the product to the cart'
      '400':
       description: 'You must login to perform this action'
      '404':
       description: 'Product not found'
      '500':
       description: 'Product already in cart'
   
   /api/cart/: 
    operationId: R403
    summary: 'R403: Change quantity of product in cart'
    description: 'AJAX request. Updates the quantity of a product in the cart of a user. Access: OWN'
    tags:
      - 'M05: Cart'

    requestBody:
      required: true
      content:
        application/json:
          schema:
           type: object
           properties:
            id:
             type: integer 
            quantity:
             type: integer
      
    responses:
      '200':
        description: 'Sucessfully updated item quantity.'
      '404':
        description: 'Product not in the cart'
      '400':
        description: 'Error updating product cart'
     
 /checkout:
  get:
   operationId: R404
   summary: 'R404: Checkout Form'
   description: 'Provide checkout form. Access: USR'
   tags:
    - 'M05: Cart'
   responses:
        '200':
         description: 'Ok. Show checkout form'
  post:
    operationId: R405
    summary: 'R405: Checkout'
    description: 'Processes the checkout. Access: OWN'
    tags: 
     - 'M05: Cart'
     
    requestBody:
        required: true
        content:
         application/x-www-form-urlencoded:
          schema:
           type: object
           properties:
             address:
              type: object
              properties:
               street:
                type: string
               postal_code:
                type: string
               city: 
                type: string
               country:
                type: string
           required:
            - address
    responses:
     '302':
      description: 'Redirect after processing checkout form'
      headers:
       Location:
        schema:
         type: string
        examples:
         302Success:
          description: 'Successful checkout. Redirect to home page.'
          value: '/home'
         302Failure:
          description: 'Failed checkout. Redirect to checkout.'
          value: '/checkout'
          
        
 /about:
   get:
    operationId: R501
    summary: 'R501: View About page'
    description: 'Shows the About page. Access: PUB'
    tags: 
     - 'M02: User Administration and Static pages'
     
      
    responses:
      '200':
        description: 'OK. Show About page'
  
 /faq:
   get:
    operationId: R502
    summary: 'R502: View FAQ page'
    description: 'Shows the FAQ page. Access: PUB'
    tags: 
     - 'M02: User Administration and Static pages'
        
    responses:
     '200':
       description: 'OK. Show FAQ page'
         
 /contacts:
   get:
    operationId: R503
    summary: 'R503: View Contacts page'
    description: 'Shows the Contacts page. Access: PUB'
    tags: 
     - 'M02: User Administration and Static pages'
       
        
    responses:
     '200':
       description: 'OK. Show Contacts page'
       
...
...
